require:
  - rubocop-factory_bot
  # - rubocop-i18n
  - rubocop-rspec_rails
  - rubocop-thread_safety

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "app/javascript/**/*"
    - "bin/*"
    - "db/**schema.rb"
    - "node_modules/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 50
  Exclude:
  - "app/admin/**/*"
  - "config/routes.rb"

Metrics/MethodLength:
  Max: 20

Naming/BlockForwarding:
  EnforcedStyle: explicit

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
  - "db/migrate/**/*"

Rails/ThreeStateBooleanColumn:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/RepeatedExample:
  Exclude:
  - "spec/policies/**/"

Style/ParallelAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false


# To fix over time
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
