local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

scaleway:
  service: S3
  access_key_id: <%= ENV.fetch("SCALEWAY_ACCESS_KEY_ID", "") %>
  secret_access_key: <%= ENV.fetch("SCALEWAY_ACCESS_KEY_SECRET", "") %>
  region: <%= ENV.fetch("SCALEWAY_REGION", "") %>
  bucket: <%= ENV.fetch("SCALEWAY_BUCKET_NAME", "") %>
  endpoint: <%= ENV.fetch("SCALEWAY_ENDPOINT", "") %>
